# Generated by Django 3.2.3 on 2021-05-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='Arac_Kimligi',
        ),
    ]
